### ISSUE TITLE
vagrant-hostsupdater install problem

### ISSUE THREAD

**Issue by machulnyy** [Varying-Vagrant-Vagrants/VVV#1002]
Hi all,

I install VirtualBox then Vagrant. Following instruction for VVV, I try to install the plugins by typing:

`vagrant plugin install vagrant-hostsupdater`

And then I get the following: 

```
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:85:in `mkdir': Permission denied @ dir_s_mkdir - /Users/danny/.bundle/cache/compact_index/gems.hashicorp.com.443.68db9b3ad4be8461ccdecca2ae96d12a/versions20161015-2857-1r799sf (Errno::EACCES)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:85:in `block in mktmpdir'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:129:in `create'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/tmpdir.rb:85:in `mktmpdir'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:230:in `block in internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:294:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/user_interaction.rb:45:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:293:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:229:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/bundler.rb:102:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:174:in `<main>'
```

What am I doing wrong? Second evening racking my brain how to set up a Local Wordpress Development Environment and I am nowhere closer to my goal. Please help! Thanks!

Update: tried using host manager instead. Similar thing happens

**Comment by cfoellmann** [comment]
Non-root/Admin console?

**Comment by machulnyy** [comment]
Sorry don't know what that means...

**Comment by cfoellmann** [comment]
Are you on Linux? OS X? Windows?
Suspecting Linux: `sudo vagrant plugin install vagrant-hostsupdater`

**Comment by cfoellmann** [comment]
I suspect you need to run your command with admin rights.

**Comment by machulnyy** [comment]
OS X. Sierra. Thank you for looking into this...

**Comment by machulnyy** [comment]
it worked. you sir are a genius, thank you.

typed in 

> sudo vagrant plugin install vagrant-hostsupdater

and voila 

> Installed the plugin 'vagrant-hostsupdater (1.0.2)'!

**Comment by nerrad** [comment]
Congratulations on joining the world of VVV @machulnyy.  For future reference, since it appears you're new to doing things command line in the terminal.  You'll want to search for some documentation on the usage of the `sudo` command.  Basically you use this to execute other commands with administrative permissions on your machine as without that you are just executing the command with whatever permissions your current user has.  On MacOSx, most low level system utility commands need to be executed with the sudo command (which is why you encountered the error you did).

You'll find that much of what you do with VVV involves working in the command line at one point or another so its a great opportunity for you to learn more about working in the Terminal.
