### ISSUE TITLE
npm not working from host side (unsure if should be ran in guest or host)

### ISSUE THREAD

**Issue by srosano** [Varying-Vagrant-Vagrants/VVV#1660]
Hello, 

I have provided this information as required. Happy to hear thoughts and opinions, and learn more about vagrant. 

Expected Behaviour?
First I initially git clone the FoundationPress repo (https://github.com/olefredrik/FoundationPress) into the WordPress theme's folder and then I run "npm install" and "npm start". This works the first time and broswersync works and you can see the changes - beautiful.

However the problem is when I run "vagrant halt" and then later come back and run "vagrant up" I find that when I return to the theme's folder to run "npm start" again it doesn't work. 

I am not sure if I am doing this correctly or if vagrant require's me to do it a certain way. 

Current Behaviour:
Here is the log I see when re-running it from the hosts' side again:
> foundationpress@2.10.4 start /home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress
> gulp

[17:35:56] Failed to load external module @babel/register
[17:35:56] Requiring external module babel-register
[17:35:56] Loading config file...
[17:35:56] config.yml exists, loading config.yml
[17:35:56] Using gulpfile ~/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/gulpfile.babel.js
[17:35:56] Starting 'default'...
[17:35:56] Starting 'build'...
[17:35:56] Starting 'clean'...
[17:35:56] Finished 'clean' after 25 ms
[17:35:56] Starting 'sass'...
[17:35:56] Starting 'webpack:build'...
[17:35:56] Starting 'images'...
[17:35:56] Starting 'copy'...
[17:35:57] Finished 'copy' after 451 ms
[17:35:57] Finished 'images' after 521 ms
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("spin")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("spin")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("wiggle")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("wiggle")) instead.

[17:35:59] Version: webpack 3.12.0
 Asset    Size  Chunks                    Chunk Names
app.js  404 kB       0  [emitted]  [big]  app
[17:35:59] Finished 'sass' after 2.91 s
[17:35:59] Finished 'webpack:build' after 2.91 s
[17:35:59] Finished 'build' after 2.93 s
[17:35:59] Starting 'server'...
[17:35:59] Finished 'server' after 31 ms
[17:35:59] Starting 'webpack:watch'...
[17:35:59] Starting 'watch'...
[17:35:59] 'watch' errored after 239 ms
[17:35:59] Error: watch node_modules/component-bind ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
[17:35:59] 'default' errored after 3.21 s
[17:35:59] The following tasks did not complete: webpack:watch
[17:35:59] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foundationpress@2.10.4 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foundationpress@2.10.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sparky/.npm/_logs/2018-10-26T06_36_00_000Z-debug.log

Details from the debug log (/home/sparky/.npm/_logs/2018-10-26T06_36_00_000Z-debug.log):

0 info it worked if it ends with ok
1 verbose cli [ '/home/sparky/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/home/sparky/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foundationpress@2.10.4~prestart: foundationpress@2.10.4
6 info lifecycle foundationpress@2.10.4~start: foundationpress@2.10.4
7 verbose lifecycle foundationpress@2.10.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle foundationpress@2.10.4~start: PATH: /home/sparky/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress/node_modules/.bin:/home/sparky/.nvm/versions/node/v8.11.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle foundationpress@2.10.4~start: CWD: /home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress
10 silly lifecycle foundationpress@2.10.4~start: Args: [ '-c', 'gulp' ]
11 silly lifecycle foundationpress@2.10.4~start: Returned: code: 1  signal: null
12 info lifecycle foundationpress@2.10.4~start: Failed to exec start script
13 verbose stack Error: foundationpress@2.10.4 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/sparky/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/sparky/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid foundationpress@2.10.4
15 verbose cwd /home/sparky/dev/vvv/www/chromatix/htdocs/wp-content/themes/FoundationPress
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/home/sparky/.nvm/versions/node/v8.11.1/bin/node" "/home/sparky/.nvm/versions/node/v8.11.1/bin/npm" "start"
18 verbose node v8.11.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error foundationpress@2.10.4 start: `gulp`
22 error Exit status 1
23 error Failed at the foundationpress@2.10.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Possible Solution:
If it worked the first time, I am thinking maybe a permissions issue? 

Happy to provide any additional information - would like to further my understanding of this issue. 

My Environment:
VVV version: 2.3.0 Master
VVV Git Branch: Master Branch
Vagrant version: Vagrant 2.2.0
VM Provider name: VirtualBox
VM Provider version: Version 5.2.20 r125813 (Qt5.7.1
Operating System and version: Debian 9 (Linux ethos 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux) 

npm -v
6.4.1

node -v
v8.11.1

**Comment by tomjn** [comment]
to run `npm` on the host you need to install `npm` on the host. If you're running it on the host, then it doesn't matter if it's in VVV or just on your desktop, this is either an `npm` issue or a Foundationpress issue

**Comment by srosano** [comment]
Hey mate,

turns out I think I needed to download npm webpack. 

I'll leave this comment here incase someone else has the same problem. 

Kind Regards,
Scotty
