### ISSUE TITLE
VirtualBox 6

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1692]
@tomjn 
I have tested VirtualBox 6 with Vagrant 2.2.2 and Latest Develop branch. I also did a vagrant destroy and vagrant up. It seems it is getting stucked at 

Adding ppa:git-core/ppa repository and is not doing anything else. 

```
Docs:       https://varyingvagrantvagrants.org/
Contribute: https://github.com/varying-vagrant-vagrants/vvv
Dashboard:  http://vvv.test

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: WordPress_a5b8b655409
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 6.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.dev
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.local
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 vvv.localhost
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 getbenonit.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 initiator.test
==> default: [vagrant-hostsupdater]   found entry for: 192.168.50.4 sandbox.test
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/log => /Users/benlumia007/WordPress/log
    default: /srv/www => /Users/benlumia007/WordPress/www
    default: /vagrant => /Users/benlumia007/WordPress
    default: /srv/config => /Users/benlumia007/WordPress/config
    default: /srv/database => /Users/benlumia007/WordPress/database
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: default (shell)...
    default: Running: /var/folders/3z/wybjrbm92kn0ccq0fh7hqtx00000gn/T/vagrant-shell20181219-2407-lq70n2.sh
    default: /tmp/vagrant-shell: line 10: provision-network-functions.sh: No such file or directory
    default: /tmp/vagrant-shell: line 688: network_check: command not found
    default: Bash profile setup and directories.
    default:  * Copied /srv/config/bash_profile                      to /home/vagrant/.bash_profile
    default:  * Copied /srv/config/bash_aliases                      to /home/vagrant/.bash_aliases
    default:  * Copied /srv/config/vimrc                             to /home/vagrant/.vimrc
    default:  * Copied /srv/config/subversion-servers                to /home/vagrant/.subversion/servers
    default:  * Copied /srv/config/subversion-config                 to /home/vagrant/.subversion/config
    default: /tmp/vagrant-shell: line 694: network_check: command not found
    default:  
    default: Main packages check and install.
    default: Adding ppa:git-core/ppa repository
```

**Comment by benlumia007** [comment]
```
ç^C/opt/vagrant/embedded/gems/2.2.2/gems/concurrent-ruby-1.1.3/lib/concurrent/collection/map/mri_map_backend.rb:18:in `synchronize': can't be called from trap context (ThreadError)
	from /opt/vagrant/embedded/gems/2.2.2/gems/concurrent-ruby-1.1.3/lib/concurrent/collection/map/mri_map_backend.rb:18:in `[]='
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n.rb:358:in `normalize_key'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n.rb:298:in `normalize_keys'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:84:in `lookup'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n/backend/base.rb:30:in `translate'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n.rb:185:in `block in translate'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n.rb:181:in `catch'
	from /opt/vagrant/embedded/gems/2.2.2/gems/i18n-1.1.1/lib/i18n.rb:181:in `translate'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:59:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:49:in `block in fire_callbacks'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:49:in `each'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:49:in `fire_callbacks'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:33:in `block (2 levels) in register'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/batch_action.rb:127:in `join'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/batch_action.rb:127:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/batch_action.rb:65:in `each'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/batch_action.rb:65:in `run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:280:in `block (2 levels) in batch'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:275:in `tap'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:275:in `block in batch'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:274:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:274:in `batch'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/up/command.rb:97:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/bin/vagrant:164:in `<main>'
```
I think vagrant 2.2.2 isn't compatible yet if you do a clean install, but doing vagrant up without destroying the box seems fine.
