### ISSUE TITLE
Cant fire vagrant up because of missing hostsmanager plugin

### ISSUE THREAD

**Issue by mb-sven** [Varying-Vagrant-Vagrants/VVV#1821]
Hello, I installed VVV as described on the website. With all the software requirements beforehand. VVV needs the vagrant-hostsmanager, but when I try too install it when i start with vagrant up I get this error message:

```Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:652:in encode': incomplete "\x00" on UTF-16LE (Encoding::InvalidByteSequenceError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:652:in `read'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:67:in `read_s'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:119:in `block (5 levels) in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `find'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `block (4 levels) in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:116:in `block (3 levels) in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:612:in `each_key'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:115:in `block (2 levels) in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:114:in `block in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:91:in `get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:21:in `get_resolv_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1002:in `default_config_hash'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1019:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:358:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:516:in `fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:429:in `block in validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:427:in `validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:335:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/bundler.rb:133:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:59:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:58:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/command/install.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in 'execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in 'cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:182:in '<main>'
```

I googled the issue but couldnt find a case similar to mine. I tried to reinstall everything.

What can I do? 

Best regards!

**Comment by benlumia007** [comment]
instead of installing `vagrant-hostmanger`, you need `vagrant-hostsupdater`

**Comment by Mte90** [comment]
The error doesn't mention the hostsmanager plugin but seems an issue with ruby on windows.
ALso as said @benlumia007 the plugin name is `vagrant-hostsupdater` whewre id you see a reference about hostmanager?

**Comment by tomjn** [comment]
Also, VVV will try to install it automatically on your first vagrant up, but I'm not familiar with the hostmanager plugin, what was the command you ran?

**Comment by mb-sven** [comment]
>instead of installing `vagrant-hostmanger`, you need `vagrant-hostsupdater` ...

@benlumia007 maybe i got the names wrong. But I get the same error message with vagrant-hostsupdater...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mb-sven** [comment]
>The error doesn't mention the hostsmanager plugin but seems an issue with ruby on windows. ...

@Mte90 same error message... I try to reinstall ruby maybe that helps 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mb-sven** [comment]
>Also, VVV will try to install it automatically on your first vagrant up, but I'm not familiar with the hostmanager plugin, what was the command you ran?

@tomjn I know, that’s when the error message comes up 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benlumia007** [comment]
make sure that the hosts file has permission to be written.  usually i find it useful is go to that hosts file and go to properties and security, and set user with full write permission. that may be the problem even if you install the plugin, it should have the ability to write.

**Comment by tomjn** [comment]
Vagrant comes with its own copy of Ruby that it uses, there's no need to install a copy yourself. This looks like an issue with vagrant itself, I'd suggest raising an issue either on the main vagrant github repo, or on the vagrant hostsupdater repo. The only other suggestion I can make is to clean out your vagrant install and once it's uninstalled, visit vagrantup.com and grab a fresh installer
