### ISSUE TITLE
Permission denied on vagrant up with Ubuntu 12.04

### ISSUE THREAD

**Issue by philipjohn** [Varying-Vagrant-Vagrants/VVV#261]
OS: Ubuntu 12.04 LTS
Vagrant: 1.4.3
VirtualBox: 4.2.22

Just trying to get VVV up and running and the install appeared to go smoothly until it came to 'vagrant up' which produced the following;

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise32'...
Progress: 90%/opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:204:in `initialize': Permission denied - /home/philipjohn/vagrant-local/.vagrant/machines/default/virtualbox/id (Errno::EACCES)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:204:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:204:in `open'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:204:in `id='
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/providers/virtualbox/action/import.rb:15:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/providers/virtualbox/action/customize.rb:40:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

I tried,
- CHMOD the entire vagrant-local dir to 777
- 'sudo vagrant up'
- completely uninstall everything and try again but using sudo
- $ chmod -R 777 /opt/vagrant

I still get the same issue whatever I try. Any ideas why this might be and how I can resolve?

Cheers

**Comment by andrewdonskikh** [comment]
Amazing! spent same 4 hours with same question! Thank you!

**Comment by anuj4ufriends** [comment]
What did you actually do there? Can some one help me with http://stackoverflow.com/questions/30734729/booting-up-vagrant-from-jenkins-throws-permission-denied

**Comment by inandi** [comment]
Need help !!!!

Above solution didnt work for me 

```
dynaguest@14 vfde-ose % find  /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines/ -exec ls -al {} \;
total 0
drwxr-xr-x  3 dynaguest  staff   96 Jul  3 19:20 .
drwxr-xr-x  4 root       staff  128 Jul  3 19:20 ..
drwxr-xr-x  3 dynaguest  staff   96 Jul  3 19:20 default
total 0
drwxr-xr-x   3 dynaguest  staff   96 Jul  3 19:20 .
drwxr-xr-x   3 dynaguest  staff   96 Jul  3 19:20 ..
drwxr-xr-x  11 dynaguest  staff  352 Jul  3 19:23 virtualbox
total 72
drwxr-xr-x  11 dynaguest  staff   352 Jul  3 19:23 .
drwxr-xr-x   3 dynaguest  staff    96 Jul  3 19:20 ..
-rw-r--r--   1 dynaguest  staff    40 Jul  3 19:23 action_provision
-rw-r--r--   1 dynaguest  staff    10 Jul  3 19:20 action_set_name
-rw-r--r--   1 dynaguest  staff   105 Oct 14 12:59 box_meta
-rw-r--r--   1 dynaguest  staff     1 Jul  3 19:20 creator_uid
-rw-r--r--   1 dynaguest  staff    36 Jul  3 19:20 id
-rw-r--r--   1 dynaguest  staff    32 Jul  3 19:20 index_uuid
-rw-------   1 dynaguest  staff  1675 Jul  3 19:21 private_key
-rw-r--r--   1 dynaguest  staff   882 Oct 14 12:59 synced_folders
-rw-r--r--   1 dynaguest  staff    41 Jul  3 19:20 vagrant_cwd
-rw-r--r--  1 dynaguest  staff  882 Oct 14 12:59 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/synced_folders
-rw-r--r--  1 dynaguest  staff  1 Jul  3 19:20 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/creator_uid
-rw-r--r--  1 dynaguest  staff  10 Jul  3 19:20 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/action_set_name
-rw-------  1 dynaguest  staff  1675 Jul  3 19:21 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/private_key
-rw-r--r--  1 dynaguest  staff  41 Jul  3 19:20 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/vagrant_cwd
-rw-r--r--  1 dynaguest  staff  105 Oct 14 12:59 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/box_meta
-rw-r--r--  1 dynaguest  staff  40 Jul  3 19:23 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/action_provision
-rw-r--r--  1 dynaguest  staff  36 Jul  3 19:20 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/id
-rw-r--r--  1 dynaguest  staff  32 Jul  3 19:20 /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines//default/virtualbox/index_uuid
dynaguest@14 vfde-ose % sudo chown dynaguest:staff  /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines/default/virtualbox/action_set_name
dynaguest@14 vfde-ose % sudo chown dynaguest:staff  /Users/dynaguest/Public/projects/vfde-ose/.vagrant/machines/default/virtualbox/id 
```

**Comment by Mte90** [comment]
Do you have this issue with VVV?
We are talking of a ticket of 4 years ago so it is better to open a new one with updated info about versioning of the various tools

**Comment by inandi** [comment]
@Mte90 ok, I will open a new ticket 👍but what is VVV? I want to use 'vagrant' without 'sudo'.

**Comment by Mte90** [comment]
VVV is this vagrant project for a wordpress dev environment, so if you have no idea of that probably you need to open the ticket to Vagrant itself.

**Comment by inandi** [comment]
thanks for the tip @Mte90

**Comment by tomjn** [comment]
Also, avoid using `sudo` with vagrant, you're probably going to have to destroy and recreate your VM to get it working without sudo
