### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by szepeviktor** [Varying-Vagrant-Vagrants/VVV#551]
```
==> default: Fetching external item into 'tests/phpunit/data/plugins/wordpress-importer':
==> default: Updated external to revision 1072038.
==> default: At revision 31255.
==> default: Updating npm packages...
==> default: Initializing grunt in WordPress develop... This may take a few moments.
==> default: module.js:340 <-RED
==> default:     throw err;
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default:
==> default: ^
==> default: Error: Cannot find module 'coffee-script'
==> default:     at Function.Module._resolveFilename (module.js:338:15)
==> default:     at Function.Module._load (module.js:280:25)
==> default:     at Module.require (module.js:364:17)
==> default:     at require (module.js:380:17)
==> default:     at Object.<anonymous> (/srv/www/wordpress-develop/node_modules/grunt/lib/grunt.js:16:1)
==> default:     at Module._compile (module.js:456:26)
==> default:     at Object.Module._extensions..js (module.js:474:10)
==> default:     at Module.load (module.js:356:32)
==> default:     at Function.Module._load (module.js:312:12)
==> default:     at Module.require (module.js:364:17)  <-RED
==> default: PHPMyAdmin already installed.
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default:  * Added vvv.dev from /srv/www/vvv-hosts
==> default:  * Added local.wordpress.dev from /srv/www/vvv-hosts
```

There are a lot of RED lines (last and first marked with ` <-RED`)
Windows 7 Pro 64-bit Virtualbox 4.3.16.

**Comment by szepeviktor** [comment]
There are other single red lines like `==> default: stdin: is not a tty` after `default: Running: inline script`.

**Comment by cfoellmann** [comment]
I got the same error. So it is not just you. 
Your additions in the comment are "normal". They don't hurt but we have no solution, yet. #610
