### ISSUE TITLE
Error during provision process

### ISSUE THREAD

**Issue by fa7ad** [Varying-Vagrant-Vagrants/VVV#577]
Hello, 
I cloned the repo today and tried to setup a vagrant box, during the provisioning this was part of the output in red color (I assume its stderr).
```
==> default: /srv/www/wordpress-develop/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
==> default:     }).flatten().uniq().value();
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: ^
==> default: TypeError: Object Gruntfile.js has no method 'flatten'
==> default:     at Object.module.exports [as findup] (/srv/www/wordpress-develop/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
==> default:     at Task.task.init (/srv/www/wordpress-develop/node_modules/grunt/lib/grunt/task.js:427:16)
==> default:     at Object.grunt.tasks (/srv/www/wordpress-develop/node_modules/grunt/lib/grunt.js:120:8)
==> default:     at Object.module.exports [as cli] (/srv/www/wordpress-develop/node_modules/grunt/lib/grunt/cli.js:38:9)
==> default:     at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:45:20)
==> default:     at Module._compile (module.js:456:26)
==> default:     at Object.Module._extensions..js (module.js:474:10)
==> default:     at Module.load (module.js:356:32)
==> default:     at Function.Module._load (module.js:312:12)
==> default:     at Function.Module.runMain (module.js:497:
```
Personally, I only use **wordpress_default** so, its not much of an issue, but I still think you guys should look at it :smile:

**Comment by jeremyfelt** [comment]
Thanks @fa7ad, I'm guessing this is directly related to #572. I've left a comment there on a possible cause.
