### ISSUE TITLE
Vagrant halt fails

### ISSUE THREAD

**Issue by mbootsman** [Varying-Vagrant-Vagrants/VVV#855]
Getting this error when doing `vagrant halt`:

`The command "vagrant ssh -c 'vagrant_halt'" returned a failed exit code. The
error output is shown below:

/usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler.rb:194:in `root'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `bundle_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:439:in `configure_gem_home'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:431:in `configure_gem_home_and_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `configure'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:153:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `setup'
	from /usr/bin/vagrant:75:in `<main>'
`

**Comment by mbootsman** [comment]
Updating vagrant version 1.7.4 to 1.8.1 did the trick.
