### ISSUE TITLE
Forcing shutdown of VM... Destroying VM and associated drives...

### ISSUE THREAD

**Issue by jitendraharpalani** [Varying-Vagrant-Vagrants/VVV#859]
I am on Windows Vista 32bit. I have already enabled Intel Virtualizationin in BIOS. 

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:60:in `connect_nonblock': Invalid argument - connect(2) for 127.0
.0.1:2222 (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:60:in `rescue in connect_internal'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:53:in `connect_internal'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:140:in `connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:338:in `block in tcp'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:232:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:232:in `foreach'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/socket.rb:328:in `tcp'
        from C:/Users/sunil/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/transport/session.rb:70:in `initialize'
        from C:/Users/sunil/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `new'
        from C:/Users/sunil/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:389:in `blo
ck (2 levels) in connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:368:in `blo
ck in connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:367:in `con
nect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:64:in `bloc
k in wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:42:in `wait
_for_ready'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/wait_for_communicator.rb:1
6:in `block in call'
```

**Comment by hirazi** [comment]
Apparently, GIT was not installed properly on my machine which was causing issues with `vagrant ssh`. [Reference](http://blog.osteel.me/posts/2015/01/25/how-to-use-vagrant-on-windows.html)

After re-installing GIT properly / adding GIT to Path Variable, I was able to move forward, but to face another issue: 

`64 bit host not supported` As I am using Windows Vista 32 bit, I changed my Vagrant file to update the box from ubuntu/trusty64 to ubuntu/trusty32 which fixed the issue and I moved on to a new problem of network issues on my host. 

Finally, I found a [workaround](https://gist.github.com/a93ushakov/d245f7c6fe51462416e9). After updating Vagrantfile to add network configuration as shown, my vagrant ran like a peach. 

One more thing which helped me was to enable vagrant GUI in Vagrantfile as that gave me a good detail of what's happening behind the scene. 

```
config.vm.provider :virtualbox do |vb|
	vb.gui = true
 end
```

NOTE: Remember to check `vagrant status` in the interim stages to know the exact state of your machine.

**Comment by yomok** [comment]
I'm having the same problems as you did. So can you clarify these aspects of your solution:

1)After re-installing GIT properly / adding GIT to Path Variable, I was able to move forward, but to face another issue:
How do you add GIT to Path variable?

2)64 bit host not supported As I am using Windows Vista 32 bit, I changed my Vagrant file to update the box from ubuntu/trusty64 to ubuntu/trusty32 which fixed the issue and I moved on to a new problem of network issues on my host. 

I too am on 32 bit so I would like to know how you updated the box from ubuntu/trusty64 to ubuntu/trusty32

3)Finally, I found a workaround. After updating Vagrantfile to add network configuration as shown, my vagrant ran like a peach. 

The workaround link is no longer there, what was it?
